import * as z from 'zod';
/**
 * The contracts for cases: case.json, which says what a person does, and reference.json, which
 * records what Excel showed at each checkpoint.
 */
import {
  cellAddressSchema,
  cellObservationSchema,
  selectionObservationSchema,
  stepSchema,
} from '../sheet/index.ts';

export const checkpointSchema = z
  .strictObject({
    step: z.number().int().min(0).meta({
      description: 'The index, in case.json’s steps, of the observe step this checkpoint records.',
    }),
    cells: z
      .record(cellAddressSchema, cellObservationSchema)
      .meta({ description: 'Each observed cell, by address, in the order the step listed them.' }),
    selection: selectionObservationSchema
      .optional()
      .meta({ description: 'The selection, at an observe-selection step.' }),
  })
  .meta({
    description: 'What the sheet showed at one checkpoint: an observe or observe-selection step.',
  });

export type Checkpoint = z.output<typeof checkpointSchema>;

export const referenceSchema = z
  .strictObject({
    recordedAt: z.iso.datetime().meta({ description: 'When Excel was observed.' }),
    environment: z.string().min(1).meta({
      description:
        'Which product and regional format produced the recording. Dates and numbers are read differently between regions.',
    }),
    checkpoints: z.array(checkpointSchema).meta({
      description:
        'What Excel showed at each observe step, in order: the ground truth the clone is compared against.',
    }),
  })
  .meta({
    description:
      'Excel’s recorded trajectory for one case. Written only by `factory case record`, from two runs that agreed; never edited by hand.',
  });

export type Reference = z.output<typeof referenceSchema>;

/** Labels that cut across areas. Each one is documented where it's declared. */
export const CASE_TAGS = {
  /** The end-to-end walkthrough that must pass identically on Excel and on the clone. */
  golden: 'golden',
  /**
   * Kept from the agent that builds a clone, so the final check can tell whether it learned the
   * rules or fitted the cases it saw. Held-out cases test rules the other cases also show.
   */
  heldOut: 'held-out',
  /** Generated by `factory case explore` from a seed, rather than written by a person. */
  explored: 'explored',
} as const;

export const caseSchema = z
  .strictObject({
    description: z
      .string()
      .min(1)
      .meta({ description: 'The behaviour this case pins down, as one sentence.' }),
    tags: z
      .array(z.enum(Object.values(CASE_TAGS)))
      .default([])
      .meta({
        description: 'Labels that cut across areas, such as "golden" or "held-out". See CASE_TAGS.',
      }),
    steps: z
      .array(stepSchema)
      .min(1)
      .refine(
        (steps) => steps.some((step) => step.do === 'observe' || step.do === 'observe-selection'),
        {
          error: 'needs at least one observe or observe-selection step, or nothing is recorded',
        },
      )
      .meta({
        description:
          'What to do, in order, starting from a blank sheet, or from seed.xlsx in the case’s folder if there is one.',
      }),
  })
  .meta({
    description:
      'A scenario to run on a sheet. Its id is its folder path under cases/, such as functions/sum/ignores-text.',
  });

export type Case = z.output<typeof caseSchema>;

export const verdictSchema = z
  .strictObject({
    id: z.string().meta({ description: 'The case’s id.' }),
    tags: z.array(z.string()).meta({
      description: 'The case’s tags, so verdicts can be counted by kind, such as held-out.',
    }),
    passed: z
      .boolean()
      .meta({ description: 'Whether the clone matched Excel at every checkpoint.' }),
    problems: z.array(z.string()).meta({
      description: 'Each difference from Excel, or the reason the case couldn’t run.',
    }),
  })
  .meta({ description: 'How one case went on a clone.' });

export type Verdict = z.output<typeof verdictSchema>;

export const exploreOptionsSchema = z
  .strictObject({
    seed: z.coerce.number().int().min(0).meta({
      description: 'Where the random sequences start; the same seed always gives the same cases.',
    }),
    count: z.coerce
      .number()
      .int()
      .min(1)
      .max(50)
      .meta({ description: 'How many sequences to generate and record.' }),
    steps: z.coerce
      .number()
      .int()
      .min(1)
      .max(20)
      .meta({ description: 'How many gestures each sequence makes.' }),
  })
  .meta({ description: 'What `factory case explore` was asked to do.' });
